export class UterusTemplate {
    organization: string;
    fullName: string;
    birthday: string;
    form: string;
    departament: string;
    number: string;
    currentDate: string;
    currentDate1: Date;
    lastMenstruation: string;
    phase: string;
    pause: string;
    placement: string;
    uterusLength: string;
    uterusSize: string;
    uterusWidth: string;
    miometrii: string;
    miometriiDetails: string;
    miometriiDetails1:string;
    miometriiDetails2:string;
    miometriiDetails3:string;
    miometriiDetails4:string;
    miometriiDetails5:string;
    miometriiDetails6:string;
    miometriiDetails7:string;
    miometriiDetails8:string;
    miometriiDetails9:string;
    miometriiDetails10:string;
    miometriiDetails11:string;
    miometriiDetails12:string;
    miometriiDetails13:string;
    miometriiDetails14:string;
    miometriiDetails15:string;
    miometriiDetails16:string; 
    miometriiDetails17:string;
    miometriiDetails18:string;
    miometriiDetails19:string;
    miometriiDetails20:string;
    miometriiDetails21:string;
    miometriiDetails22:string;
    miometriiDetails23:string;
    miometriiDetails24:string;
    miometriiMin: string;
    miometriiMax: string;
    miometriiSelect: string;
    endometrii: string;
    endometriiDetails1: string;
    endometriiDetails2: string;
    endometriiDetails3: string;
    endometriiDetails4: string;
    endometriiDetails5: string;
    endometriiDetails6: string;
    endometriiDetails7: string;
    endometriiDetails8: string;
    endometrii1: string;
    endometrii2: string;
    endometrii3: string;
    endometrii4: string;
    endometriiThickness: string;
    uterusCavity: string;
    uterusCavity1: string;
    uterusDetails1: string;
    uterusDetails2: string;
    uterusDetails3: string;
    uterusDetails4: string;
    uterusDetails5: string;
    uterusDetails6: string;
    uterusDetails7: string;
    uterusDetails8: string;
    uterusDetails9: string;
    uterusDetails10: string;
    uterusDetails11: string;
    uterusDetails12: string;
    uterusDetails13: string;
    uterusDetails14: string;
    uterusDetails15: string;
    egg: string;
    egg1: string;
    egg2: string;
    egg3: string;
    eggDetails: string;
    eggDetails1: string;
    eggDetails2: string;
    eggDetails3: string;
    eggDetails4: string;
    eggDetails5: string;
    eggDetails6: string;
    eggDetails7: string;
    eggDetails8: string;
    eggDetails9: string;
    eggDetails10: string;
    eggDetails11: string;
    eggDetails12: string;
    eggDetails13: string;
    eggDetails14: string;
    eggDetails15: string;
    eggDetails16: string;
    eggDetails17: string;
    eggDetails18: string;
    eggDetails19: string;
    eggDetails20: string;
    eggDetails21: string;
    eggDetails22: string;
    eggDetails23: string;
    eggDetails24: string;
    eggDetails25: string;
    eggDetails26: string;
    eggDetails27: string;
    eggDetails28: string;
    eggDetails29: string;
    eggDetails30: string;
    eggDetails31: string;
    cervixLength: string;
    cervixWidth: string;
    cervix: string;
    cervix1: string;
    cervix2: string;
    cervix3: string;
    cervixDetails15: string;
    cervixDetails1: string;
    cervixDetails2: string;
    cervixDetails3: string;
    cervixDetails4: string;
    cervixDetails5: string;
    cervixDetails6: string;
    cervixDetails7: string;
    cervixDetails8: string;
    cervixDetails9: string;
    cervixDetails10: string;
    cervixDetails11: string;
    cervixDetails12: string;
    cervixDetails13: string;
    cervixDetails14: string;
    cervicalCanal: string;
    cervicalCanal1: string;
    cervicalCanal2: string;
    cervicalCanal3: string;
    cervicalDetails1: string;
    cervicalDetails2: string;
    cervicalDetails3: string;
    cervicalDetails4: string;
    cervicalDetails5: string;
    cervicalDetails6: string;
    cervicalDetails7: string;
    cervicalDetails8: string;
    cervicalDetails9: string;
    cervicalDetails10: string;
    cervicalDetails11: string;
    cervicalDetails12: string;
    cervicalDetails13: string;
    rightLength: string;
    rightThickness: string;
    rightWidth: string;
    right: string;
    rightStructure: string;
    rightStructure1: string;
    rightStructure2: string;
    rightStructure3: string;
    rightDetails1: string;
    rightDetails2: string;
    rightDetails3: string;
    rightDetails4: string;
    rightDetails5: string;
    rightDetails6: string;
    rightDetails7: string;
    rightDetails8: string;
    rightDetails9: string;
    rightDetails10: string;
    rightDetails11: string;
    rightDetails12: string;
    rightDetails13: string;
    rightDetails14: string;
    rightDetails15: string;
    rightDetails16: string;
    rightDetails17: string;
    rightDetails18: string;
    rightDetails19: string;
    rightDetails20: string;
    rightDetails21: string;
    rightDetails22: string;
    rightDetails23: string;
    rightDetails24: string;
    rightDetails25: string;
    rightDetails26: string;
    rightDetails27: string;
    rightDetails28: string;
    rightDetails29: string;
    rightFolikularAparat: string;
    rightFolikularAparat1: string;
    rightTube: string;
    rightTube1: string;
    rightTube2: string;
    rightTube3: string;
    leftLength: string;
    leftThickness: string;
    leftWidth: string;
    left: string;
    leftStructure: string;
    leftStructure1: string;
    leftStructure2: string;
    leftStructure3: string;
    leftDetails1: string;
    leftDetails2: string;
    leftDetails3: string;
    leftDetails4: string;
    leftDetails5: string;
    leftDetails6: string;
    leftDetails7: string;
    leftDetails8: string;
    leftDetails9: string;
    leftDetails10: string;
    leftDetails11: string;
    leftDetails12: string;
    leftDetails13: string;
    leftDetails14: string;
    leftDetails15: string;
    leftDetails16: string;
    leftDetails17: string;
    leftDetails18: string;
    leftDetails19: string;
    leftDetails20: string;
    leftDetails21: string;
    leftDetails22: string;
    leftDetails23: string;
    leftDetails24: string;
    leftDetails25: string;
    leftDetails26: string;
    leftDetails27: string;
    leftDetails28: string;
    leftDetails29: string;
    leftFolikularAparat: string;
    leftFolikularAparat1: string;
    leftTube: string;
    leftTube1: string;
    leftTube2: string;
    leftTube3: string;
    liquid: string;
    liquidLevel: string;
    addition: string;
    formation: string;
    formationNotes: string;
    body: string;
    bodyDetails1: string;
    bodyDetails2: string;
    bodyDetails3: string;
    bodyDetails4: string;
    bodyDetails5: string;
    bodyDetails6: string;
    bodyDetails7: string;
    bodyDetails8: string;
    bodyDetails9: string;
    bodyDetails10: string;
    cavity: string;
    cavityDetails9: string;
    cavityDetails1: string;
    cavityDetails2: string;
    cavityDetails3: string;
    cavityDetails4: string;
    cavityDetails5: string;
    cavityDetails6: string;
    cavityDetails7: string;
    cavityDetails8: string;
    neck: string;
    neckDetails1: string;
    neckDetails2: string;
    neckDetails3: string;
    neckDetails4: string;
    ovaries: string;
    ovaries1: string;
    ovaries2: string;
    ovariesDetails1: string;
    ovariesDetails2: string;
    ovariesDetails3: string;
    ovariesDetails4: string;
    ovariesDetails5: string;
    ovariesDetails6: string;
    ovariesDetails7: string;
    ovariesDetails8: string;
    ovariesDetails9: string;
    ovariesDetails10: string;
    ovariesDetails11: string;
    ovariesDetails12: string;
    ovariesDetails13: string;
    ovariesDetails14: string;
    ovariesDetails15: string;
    ovariesDetails16: string;
    ovariesDetails17: string;
    ovariesDetails18: string;
    ovariesDetails19: string;
    ovariesDetails20: string;
    ovariesDetails21: string;
    ovariesDetails22: string;
    ovariesDetails23: string;
    ovariesDetails24: string;
    ovariesDetails25: string;
    ovariesDetails26: string;
    ovariesDetails27: string;
    ovariesDetails28: string;
    ovariesDetails29: string;
    ovariesDetails30: string;
    ovariesDetails31: string;
    ovariesDetails32: string;
    ovariesDetails33: string;
    ovariesDetails34: string;
    ovariesDetails35: string;
    ovariesDetails36: string;
    ovariesDetails37: string;
    ovariesDetails38: string;
    ovariesDetails39: string;
    ovariesDetails40: string;
    ovariesDetails41: string;
    ovariesDetails42: string;
    ovariesDetails43: string;
    ovariesDetails44: string;
    ovariesDetails45: string;
    ovariesDetails46: string;
    ovariesDetails47: string;
    ovariesDetails48: string;
    ovariesDetails49: string;
    ovariesDetails50: string;
    ovariesDetails51: string;
    ovariesDetails52: string;
    pregnancy: string;
    pregnancy1: string;
    pregnancyDetails1: string;
    pregnancyDetails2: string;
    pregnancyDetails3: string;
    pregnancyDetails4: string;
    pregnancyDetails5: string;
    pregnancyDetails6: string;
    pregnancyDetails7: string;
    pregnancyDetails8: string;
    pregnancyDetails9: string;
    pregnancyDetails10: string;
    ectopicSpace: string;
    cervicChannelCon: string;
    dovmt: string;
    dovmtDetails1: string;
    dovmtDetails2: string;
    dovmtDetails3: string;
    dovmtDetails4: string;
    conclusion: string;

    constructor() {
        this.organization = '';
        this.fullName = '';
        this.birthday = '';
        this.form = '';
        this.departament = '';
        this.number = '';
        this.currentDate = '';
        this.currentDate1 = new Date();
        this.lastMenstruation = '';
        this.phase = '';
        this.pause = '';
        this.placement = '';
        this.uterusLength = '';
        this.uterusSize = '';
        this.uterusWidth = '';
        this.miometrii = '';
        this.miometriiDetails = '';
        this.miometriiDetails1 = '';
        this.miometriiDetails2 = '';
        this.miometriiDetails3 = '';
        this.miometriiDetails4 = '';
        this.miometriiDetails5 = '';
        this.miometriiDetails6 = '';
        this.miometriiDetails7 = '';
        this.miometriiDetails8 = '';
        this.miometriiDetails9 = '';
        this.miometriiDetails10 = '';
        this.miometriiDetails11 = '';
        this.miometriiDetails12 = '';
        this.miometriiDetails13 = '';
        this.miometriiDetails14 = '';
        this.miometriiDetails15 = '';
        this.miometriiDetails16 = '';
        this.miometriiDetails17 = '';
        this.miometriiDetails18 = '';
        this.miometriiDetails19 = '';
        this.miometriiDetails20 = '';
        this.miometriiDetails21 = '';
        this.miometriiDetails22 = '';
        this.miometriiDetails23 = '';
        this.miometriiDetails24 = '';
        this.miometriiMin = '';
        this.miometriiMax = '';
        this.miometriiSelect = '';
        this.endometrii = '';
        this.endometriiDetails1 = '';
        this.endometriiDetails2 = '';
        this.endometriiDetails3 = '';
        this.endometriiDetails4 = '';
        this.endometriiDetails5 = '';
        this.endometriiDetails6 = '';
        this.endometriiDetails7 = '';
        this.endometriiDetails8 = '';
        this.endometrii1 = '';
        this.endometrii2 = '';
        this.endometrii3 = '';
        this.endometrii4 = '';
        this.endometriiThickness ='';
        this.uterusCavity = '';
        this.uterusCavity1 = '';
        this.uterusDetails1 = '';
        this.uterusDetails2 = '';
        this.uterusDetails3 = '';
        this.uterusDetails4 = '';
        this.uterusDetails5 = '';
        this.uterusDetails6 = '';
        this.uterusDetails7 = '';
        this.uterusDetails8 = '';
        this.uterusDetails9 = '';
        this.uterusDetails10 = '';
        this.uterusDetails11 = '';
        this.uterusDetails12 = '';
        this.uterusDetails13 = '';
        this.uterusDetails14 = '';
        this.uterusDetails15 = '';
        this.egg = '';
        this.egg1 = '';
        this.egg2 = '';
        this.egg3 = '';
        this.eggDetails = '';
        this.eggDetails1 = '';
        this.eggDetails2 = '';
        this.eggDetails3 = '';
        this.eggDetails4 = '';
        this.eggDetails5 = '';
        this.eggDetails6 = '';
        this.eggDetails7 = '';
        this.eggDetails8 = '';
        this.eggDetails9 = '';
        this.eggDetails10 = '';
        this.eggDetails11 = '';
        this.eggDetails12 = '';
        this.eggDetails13 = '';
        this.eggDetails14 = '';
        this.eggDetails15 = '';
        this.eggDetails16 = '';
        this.eggDetails17 = '';
        this.eggDetails18 = '';
        this.eggDetails19 = '';
        this.eggDetails20 = '';
        this.eggDetails21 = '';
        this.eggDetails22 = '';
        this.eggDetails23 = '';
        this.eggDetails24 = '';
        this.eggDetails25 = '';
        this.eggDetails26 = '';
        this.eggDetails27 = '';
        this.eggDetails28 = '';
        this.eggDetails29 = '';
        this.eggDetails30 = '';
        this.eggDetails31 = '';
        this.cervixLength = '';
        this.cervixWidth = '';
        this.cervix = '';
        this.cervix1 ='';
        this.cervix2 ='';
        this.cervix3 ='';
        this.cervixDetails1 = '';
        this.cervixDetails2 = '';
        this.cervixDetails3 = '';
        this.cervixDetails4 = '';
        this.cervixDetails5 = '';
        this.cervixDetails6 = '';
        this.cervixDetails7 = '';
        this.cervixDetails8 = '';
        this.cervixDetails9 = '';
        this.cervixDetails10 = '';
        this.cervixDetails11 = '';
        this.cervixDetails12 = '';
        this.cervixDetails13 = '';
        this.cervixDetails14 = '';
        this.cervixDetails15 = '';
        this.cervicalCanal = '';
        this.cervicalCanal1 ='';
        this.cervicalCanal2 ='';
        this.cervicalCanal3 ='';
        this.cervicalDetails1 ='';
        this.cervicalDetails2 ='';
        this.cervicalDetails3 ='';
        this.cervicalDetails4 ='';
        this.cervicalDetails5 ='';
        this.cervicalDetails6 ='';
        this.cervicalDetails7 ='';
        this.cervicalDetails8 ='';
        this.cervicalDetails9 ='';
        this.cervicalDetails10 ='';
        this.cervicalDetails11 ='';
        this.cervicalDetails12 ='';
        this.cervicalDetails13 ='';
        this.rightLength = '';
        this.rightThickness = '';
        this.rightWidth = '';
        this.right = '';
        this.rightStructure = '';
        this.rightStructure1 = '';
        this.rightStructure2 = '';
        this.rightStructure3 = '';
        this.rightDetails1 = '';
        this.rightDetails2 = '';
        this.rightDetails3 = '';
        this.rightDetails4 = '';
        this.rightDetails5 = '';
        this.rightDetails6 = '';
        this.rightDetails7 = '';
        this.rightDetails8 = '';
        this.rightDetails9 = '';
        this.rightDetails10 = '';
        this.rightDetails11 = '';
        this.rightDetails12 = '';
        this.rightDetails13 = '';
        this.rightDetails14 = '';
        this.rightDetails15 = '';
        this.rightDetails16 = '';
        this.rightDetails17 = '';
        this.rightDetails18 = '';
        this.rightDetails19 = '';
        this.rightDetails20 = '';
        this.rightDetails21 = '';
        this.rightDetails22 = '';
        this.rightDetails23 = '';
        this.rightDetails24 = '';
        this.rightDetails25 = '';
        this.rightDetails26 = '';
        this.rightDetails27 = '';
        this.rightDetails28 = '';
        this.rightDetails29 = '';
        this.rightFolikularAparat = '';
        this.rightFolikularAparat1 = '';
        this.rightTube = '';
        this.rightTube1 = '';
        this.rightTube2 = '';
        this.rightTube3 = '';
        this.leftLength = '';
        this.leftThickness = '';
        this.leftWidth = '';
        this.left = '';
        this.leftStructure = '';
        this.leftStructure1 = '';
        this.leftStructure2 = '';
        this.leftStructure3 = '';
        this.leftDetails1 = '';
        this.leftDetails2 = '';
        this.leftDetails3 = '';
        this.leftDetails4 = '';
        this.leftDetails5 = '';
        this.leftDetails6 = '';
        this.leftDetails7 = '';
        this.leftDetails8 = '';
        this.leftDetails9 = '';
        this.leftDetails10 = '';
        this.leftDetails11 = '';
        this.leftDetails12 = '';
        this.leftDetails13 = '';
        this.leftDetails14 = '';
        this.leftDetails15 = '';
        this.leftDetails16 = '';
        this.leftDetails17 = '';
        this.leftDetails18 = '';
        this.leftDetails19 = '';
        this.leftDetails20 = '';
        this.leftDetails21 = '';
        this.leftDetails22 = '';
        this.leftDetails23 = '';
        this.leftDetails24 = '';
        this.leftDetails25 = '';
        this.leftDetails26 = '';
        this.leftDetails27 = '';
        this.leftDetails28 = '';
        this.leftDetails29 = '';
        this.leftFolikularAparat = '';
        this.leftFolikularAparat1 = '';
        this.leftTube = '';
        this.leftTube1 = '';
        this.leftTube2 = '';
        this.leftTube3 = '';
        this.liquid = '';
        this.liquidLevel = '';
        this.addition = '';
        this.formation = '';
        this.formationNotes = '';
        this.body = '';
        this.bodyDetails1 = '';
        this.bodyDetails2 = '';
        this.bodyDetails3 = '';
        this.bodyDetails4 = '';
        this.bodyDetails5 = '';
        this.bodyDetails6 = '';
        this.bodyDetails7 = '';
        this.bodyDetails8 = '';
        this.bodyDetails9 = '';
        this.bodyDetails10 = '';
        this.cavity = '';
        this.cavityDetails1 = '';
        this.cavityDetails2 = '';
        this.cavityDetails3 = '';
        this.cavityDetails4 = '';
        this.cavityDetails5 = '';
        this.cavityDetails6 = '';
        this.cavityDetails7 = '';
        this.cavityDetails8 = '';
        this.cavityDetails9 = '';
        this.neck = '';
        this.neckDetails1 = '';
        this.neckDetails2 = '';
        this.neckDetails3 = '';
        this.neckDetails4 = '';
        this.ovaries = '';
        this.ovaries1 = '';
        this.ovaries2 = '';
        this.ovariesDetails1 = '';
        this.ovariesDetails2 = '';
        this.ovariesDetails3 = '';
        this.ovariesDetails4 = '';
        this.ovariesDetails5 = '';
        this.ovariesDetails6 = '';
        this.ovariesDetails7 = '';
        this.ovariesDetails8 = '';
        this.ovariesDetails9 = '';
        this.ovariesDetails10 = '';
        this.ovariesDetails11 = '';
        this.ovariesDetails12 = '';
        this.ovariesDetails13 = '';
        this.ovariesDetails14 = '';
        this.ovariesDetails15 = '';
        this.ovariesDetails16 = '';
        this.ovariesDetails17 = '';
        this.ovariesDetails18 = '';
        this.ovariesDetails19 = '';
        this.ovariesDetails20 = '';
        this.ovariesDetails21 = '';
        this.ovariesDetails22 = '';
        this.ovariesDetails23 = '';
        this.ovariesDetails24 = '';
        this.ovariesDetails25 = '';
        this.ovariesDetails26 = '';
        this.ovariesDetails27 = '';
        this.ovariesDetails28 = '';
        this.ovariesDetails29 = '';
        this.ovariesDetails30 = '';
        this.ovariesDetails31 = '';
        this.ovariesDetails32 = '';
        this.ovariesDetails33 = '';
        this.ovariesDetails34 = '';
        this.ovariesDetails35 = '';
        this.ovariesDetails36 = '';
        this.ovariesDetails37 = '';
        this.ovariesDetails38 = '';
        this.ovariesDetails39 = '';
        this.ovariesDetails40 = '';
        this.ovariesDetails41 = '';
        this.ovariesDetails42 = '';
        this.ovariesDetails43 = '';
        this.ovariesDetails44 = '';
        this.ovariesDetails45 = '';
        this.ovariesDetails46 = '';
        this.ovariesDetails47 = '';
        this.ovariesDetails48 = '';
        this.ovariesDetails49 = '';
        this.ovariesDetails50 = '';
        this.ovariesDetails51 = '';
        this.ovariesDetails52 = '';
        this.pregnancy = '';
        this.pregnancyDetails1 = '';
        this.pregnancyDetails2 = '';
        this.pregnancyDetails3 = '';
        this.pregnancyDetails4 = '';
        this.pregnancyDetails5 = '';
        this.pregnancyDetails6 = '';
        this.pregnancyDetails7 = '';
        this.pregnancyDetails8 = '';
        this.pregnancyDetails9 = '';
        this.pregnancyDetails10 = '';
        this.pregnancy1 = '';
        this.ectopicSpace = '';
        this.cervicChannelCon = '';
        this.dovmt = '';
        this.dovmtDetails1 = '';
        this.dovmtDetails2 = '';
        this.dovmtDetails3 = '';
        this.dovmtDetails4 = '';
        this.conclusion = '';
    }
}