export class UterusTemplate {
    organization: string;
    fullName: string;
    birthday: string;
    form: string;
    departament: string;
    number: string;
    currentDate: string;
    lastMenstruation: string;
    phase: string;
    pause: string;
    placement: string;
    uterusLength: string;
    uterusSize: string;
    uterusWidth: string;
    miometrii: string;
    endometrii: string;
    uterusCavity: string;
    cervixLength: string;
    cervixWidth: string;
    cervix: string;
    cervicalCanal: string;
    rightLength: string;
    rightThickness: string;
    rightWidth: string;
    right: string;
    rightStructure: string;
    rightTube: string;
    leftLength: string;
    leftThickness: string;
    leftWidth: string;
    left: string;
    leftStructure: string;
    leftTube: string;
    liquid: string;
    formation: string;
    body: string;
    cavity: string;
    neck: string;
    ovaries: string;
    pregnancy: string;
    ectopicSpace: string;
    dovmt: string;
    conclusion: string;

    constructor() {
        this.organization = '';
        this.fullName = '';
        this.birthday = '';
        this.form = '';
        this.departament = '';
        this.number = '';
        this.currentDate = '';
        this.lastMenstruation = '';
        this.phase = '';
        this.pause = '';
        this.placement = '';
        this.uterusLength = '';
        this.uterusSize = '';
        this.uterusWidth = '';
        this.miometrii = '';
        this.endometrii = '';
        this.uterusCavity = '';
        this.cervixLength = '';
        this.cervixWidth = '';
        this.cervix = '';
        this.cervicalCanal = '';
        this.rightLength = '';
        this.rightThickness = '';
        this.rightWidth = '';
        this.right = '';
        this.rightStructure = '';
        this.rightTube = '';
        this.leftLength = '';
        this.leftThickness = '';
        this.leftWidth = '';
        this.left = '';
        this.leftStructure = '';
        this.leftTube = '';
        this.liquid = '';
        this.formation = '';
        this.body = '';
        this.cavity = '';
        this.neck = '';
        this.ovaries = '';
        this.pregnancy = '';
        this.ectopicSpace = '';
        this.dovmt = '';
        this.conclusion = '';
    }
}