export class UterusTemplate {
    organization: string;
    fullName: string;
    birthday: string;
    form: string;
    departament: string;
    number: string;
    currentDate: string;
    currentDate1: Date;
    lastMenstruation: string;
    phase: string;
    pause: string;
    placement: string;
    uterusLength: string;
    uterusSize: string;
    uterusWidth: string;
    miometrii: string;
    miometriiDetails: string;
    miometriiDetails1:string;
    miometriiDetails2:string;
    miometriiDetails3:string;
    miometriiDetails4:string;
    miometriiDetails5:string;
    miometriiDetails6:string;
    miometriiDetails7:string;
    miometriiDetails8:string;
    miometriiDetails9:string;
    miometriiDetails10:string;
    miometriiDetails11:string;
    miometriiDetails12:string;
    miometriiDetails13:string;
    miometriiDetails14:string;
    miometriiDetails15:string;
    miometriiDetails16:string; 
    miometriiDetails17:string;
    miometriiDetails18:string;
    miometriiDetails19:string;
    miometriiDetails20:string;
    miometriiDetails21:string;
    miometriiDetails22:string;
    miometriiDetails23:string;
    miometriiDetails24:string;
    miometriiMin: string;
    miometriiMax: string;
    miometriiSelect: string;
    endometrii: string;
    endometriiDetails1: string;
    endometriiDetails2: string;
    endometriiDetails3: string;
    endometriiDetails4: string;
    endometriiDetails5: string;
    endometriiDetails6: string;
    endometriiDetails7: string;
    endometriiDetails8: string;
    endometrii1: string;
    endometrii2: string;
    endometrii3: string;
    endometrii4: string;
    endometriiThickness: string;
    uterusCavity: string;
    uterusCavity1: string;
    uterusDetails1: string;
    uterusDetails2: string;
    uterusDetails3: string;
    uterusDetails4: string;
    uterusDetails5: string;
    uterusDetails6: string;
    uterusDetails7: string;
    uterusDetails8: string;
    uterusDetails9: string;
    uterusDetails10: string;
    uterusDetails11: string;
    uterusDetails12: string;
    uterusDetails13: string;
    uterusDetails14: string;
    uterusDetails15: string;
    egg: string;
    egg1: string;
    egg2: string;
    egg3: string;
    eggDetails: string;
    eggDetails1: string;
    eggDetails2: string;
    eggDetails3: string;
    eggDetails4: string;
    eggDetails5: string;
    eggDetails6: string;
    eggDetails7: string;
    eggDetails8: string;
    eggDetails9: string;
    eggDetails10: string;
    eggDetails11: string;
    eggDetails12: string;
    eggDetails13: string;
    eggDetails14: string;
    eggDetails15: string;
    eggDetails16: string;
    eggDetails17: string;
    eggDetails18: string;
    eggDetails19: string;
    eggDetails20: string;
    eggDetails21: string;
    eggDetails22: string;
    eggDetails23: string;
    eggDetails24: string;
    eggDetails25: string;
    eggDetails26: string;
    eggDetails27: string;
    eggDetails28: string;
    eggDetails29: string;
    eggDetails30: string;
    eggDetails31: string;
    cervixLength: string;
    cervixWidth: string;
    cervix: string;
    cervix1: string;
    cervix2: string;
    cervix3: string;
    cervicalCanal: string;
    cervicalCanal1: string;
    cervicalCanal2: string;
    cervicalCanal3: string;
    rightLength: string;
    rightThickness: string;
    rightWidth: string;
    right: string;
    rightStructure: string;
    rightStructure1: string;
    rightStructure2: string;
    rightStructure3: string;
    rightFolikularAparat: string;
    rightFolikularAparat1: string;
    rightTube: string;
    rightTube1: string;
    rightTube2: string;
    rightTube3: string;
    leftLength: string;
    leftThickness: string;
    leftWidth: string;
    left: string;
    leftStructure: string;
    leftStructure1: string;
    leftStructure2: string;
    leftStructure3: string;
    leftFolikularAparat: string;
    leftFolikularAparat1: string;
    leftTube: string;
    leftTube1: string;
    leftTube2: string;
    leftTube3: string;
    liquid: string;
    liquidLevel: string;
    addition: string;
    formation: string;
    formationNotes: string;
    body: string;
    cavity: string;
    neck: string;
    ovaries: string;
    ovaries1: string;
    ovaries2: string;
    pregnancy: string;
    pregnancy1: string;
    ectopicSpace: string;
    cervicChannelCon: string;
    dovmt: string;
    conclusion: string;

    constructor() {
        this.organization = '';
        this.fullName = '';
        this.birthday = '';
        this.form = '';
        this.departament = '';
        this.number = '';
        this.currentDate = '';
        this.currentDate1 = new Date();
        this.lastMenstruation = '';
        this.phase = '';
        this.pause = '';
        this.placement = '';
        this.uterusLength = '';
        this.uterusSize = '';
        this.uterusWidth = '';
        this.miometrii = '';
        this.miometriiDetails = '';
        this.miometriiDetails1 = '';
        this.miometriiDetails2 = '';
        this.miometriiDetails3 = '';
        this.miometriiDetails4 = '';
        this.miometriiDetails5 = '';
        this.miometriiDetails6 = '';
        this.miometriiDetails7 = '';
        this.miometriiDetails8 = '';
        this.miometriiDetails9 = '';
        this.miometriiDetails10 = '';
        this.miometriiDetails11 = '';
        this.miometriiDetails12 = '';
        this.miometriiDetails13 = '';
        this.miometriiDetails14 = '';
        this.miometriiDetails15 = '';
        this.miometriiDetails16 = '';
        this.miometriiDetails17 = '';
        this.miometriiDetails18 = '';
        this.miometriiDetails19 = '';
        this.miometriiDetails20 = '';
        this.miometriiDetails21 = '';
        this.miometriiDetails22 = '';
        this.miometriiDetails23 = '';
        this.miometriiDetails24 = '';
        this.miometriiMin = '';
        this.miometriiMax = '';
        this.miometriiSelect = '';
        this.endometrii = '';
        this.endometriiDetails1 = '';
        this.endometriiDetails2 = '';
        this.endometriiDetails3 = '';
        this.endometriiDetails4 = '';
        this.endometriiDetails5 = '';
        this.endometriiDetails6 = '';
        this.endometriiDetails7 = '';
        this.endometriiDetails8 = '';
        this.endometrii1 = '';
        this.endometrii2 = '';
        this.endometrii3 = '';
        this.endometrii4 = '';
        this.endometriiThickness ='';
        this.uterusCavity = '';
        this.uterusCavity1 = '';
        this.egg = '';
        this.egg1 = '';
        this.egg2 = '';
        this.egg3 = '';
        this.eggDetails = '';
        this.eggDetails1 = '';
        this.eggDetails2 = '';
        this.eggDetails3 = '';
        this.eggDetails4 = '';
        this.eggDetails5 = '';
        this.eggDetails6 = '';
        this.eggDetails7 = '';
        this.eggDetails8 = '';
        this.eggDetails9 = '';
        this.eggDetails10 = '';
        this.eggDetails11 = '';
        this.eggDetails12 = '';
        this.eggDetails13 = '';
        this.eggDetails14 = '';
        this.eggDetails15 = '';
        this.eggDetails16 = '';
        this.eggDetails17 = '';
        this.eggDetails18 = '';
        this.eggDetails19 = '';
        this.eggDetails20 = '';
        this.eggDetails21 = '';
        this.eggDetails22 = '';
        this.eggDetails23 = '';
        this.eggDetails24 = '';
        this.eggDetails25 = '';
        this.eggDetails26 = '';
        this.eggDetails27 = '';
        this.eggDetails28 = '';
        this.eggDetails29 = '';
        this.eggDetails30 = '';
        this.eggDetails31 = '';
        this.cervixLength = '';
        this.cervixWidth = '';
        this.cervix = '';
        this.cervix1 ='';
        this.cervix2 ='';
        this.cervix3 ='';
        this.cervicalCanal = '';
        this.cervicalCanal1 ='';
        this.cervicalCanal2 ='';
        this.cervicalCanal3 ='';
        this.rightLength = '';
        this.rightThickness = '';
        this.rightWidth = '';
        this.right = '';
        this.rightStructure = '';
        this.rightStructure1 = '';
        this.rightStructure2 = '';
        this.rightStructure3 = '';
        this.rightFolikularAparat = '';
        this.rightFolikularAparat1 = '';
        this.rightTube = '';
        this.rightTube1 = '';
        this.rightTube2 = '';
        this.rightTube3 = '';
        this.leftLength = '';
        this.leftThickness = '';
        this.leftWidth = '';
        this.left = '';
        this.leftStructure = '';
        this.leftStructure1 = '';
        this.leftStructure2 = '';
        this.leftStructure3 = '';
        this.leftFolikularAparat = '';
        this.leftFolikularAparat1 = '';
        this.leftTube = '';
        this.leftTube1 = '';
        this.leftTube2 = '';
        this.leftTube3 = '';
        this.liquid = '';
        this.liquidLevel = '';
        this.addition = '';
        this.formation = '';
        this.formationNotes = '';
        this.body = '';
        this.cavity = '';
        this.neck = '';
        this.ovaries = '';
        this.ovaries1 = '';
        this.ovaries2 = '';
        this.pregnancy = '';
        this.pregnancy1 = '';
        this.ectopicSpace = '';
        this.cervicChannelCon = '';
        this.dovmt = '';
        this.conclusion = '';
    }
}